### ISSUE TITLE
1v1 results are not uploaded

### ISSUE THREAD

**Issue by enzanki-ars** [DarbyComputerClub/darbyrobocode#4]
Only melee results are uploaded

**Comment by jacobsims** [comment]
I don't think there's a simple fix. It looks like testing is being done on all containers, but deployment only happens on #0 (and rightfully so for 99% of use cases). But the results of container 1 (1v1) get discarded after the "testing" phase "passes".

**Comment by jacobsims** [comment]
Or I suppose our easy fix could be moving that step to testing (for now anyway).

**Comment by enzanki-ars** [comment]
Move upload script to regular runner. Only push if detect its using  CircleCI? I can code that part.

**Comment by jacobsims** [comment]
Can you add it to testing runner now, and add the check later? I want to see if it works.

**Comment by jacobsims** [comment]
The check should be easy though, just see if environment variable `CIRCLE_BRANCH` is `master`.

**Comment by enzanki-ars** [comment]
Will hen I get home. Should be about 40 min.

**Comment by jacobsims** [comment]
Sorry, impatient. Doing it now.

**Comment by enzanki-ars** [comment]
If you commit them individually, can you set the commit message to some form like `[Battle name] #Num results].

**Comment by jacobsims** [comment]
I sort of did that. Hopefully it is working…

**Comment by jacobsims** [comment]
[Looking good now](https://github.com/DarbyComputerClub/darbyrobocode/commit/f48225362e2ec7fdfa52bc9baeb861f2948db871). Feel free to open another issue for further improvements, but as it stands I think this one is FIXED.

😀
