### ISSUE TITLE
Improve design of battle graphic

### ISSUE THREAD

**Issue by enzanki-ars** [DarbyComputerClub/darbyrobocode#6]
https://github.com/DarbyComputerClub/darbyrobocode/commit/f22e1b7cb8f3e134fbce8140e202284815ce097c#commitcomment-15409380

I like this feature, but it is formatted in a confusing manor.  I will improve the graphical layout of these graphics and improve the parser script.

**Comment by enzanki-ars** [comment]
Sorry to add one more request, but I am having trouble reading the calculations right now.  Is it possible to add the name of the battle to the image for when we start posting results on twitter.

**Comment by jacobsims** [comment]
Yes. That would look like `melee/darby`, right?

**Comment by enzanki-ars** [comment]
Yep. I can fix the formatting some other time. I just would like somewhere to put it.
